### ISSUE TITLE
Can't build source code

### ISSUE THREAD

**Issue by vStar925** [ermaccer/MKDHook#1]
I downloaded the source code and after making a few changes, when I go to build it in VS I get the error

Error	MSB3073	The command "rebuild.bat" exited with code 1

I looked at the .bat file in Notepad and noticed it is referring to PS2sdk which I assume is [this?](https://github.com/ps2dev/ps2sdk). I put it in the same folder tried to build again but had to luck. The bat mentions

del /s *.o
../ps2sdk/ee/bin/vsmake

I don't have a bin folder in the PS2sdk I downloaded and I'm not sure if that location refers to a specific location I have to store the file for it to build properly :\

![image](https://user-images.githubusercontent.com/100389738/182423386-c3a6cdea-b320-4db6-8ae5-7634f0c284cc.png)

![image](https://user-images.githubusercontent.com/100389738/182423439-cbd74724-3223-4cd7-980e-a305e254e849.png)

**Comment by ermaccer** [comment]
Hi, didn't actually expect someone to try and compile this so didn't bother with building instructions too much, sorry!

Quick guide:
- Download https://github.com/ThirteenAG/ps2sdk
- Make "external" folder near solution file, paste ps2sdk into
- build

**Comment by vStar925** [comment]
I was able to get it to build. I had to put them all on the desktop, not in a folder. I have an .elf file now but the game will no longer start when I put it in the scripts folder. I tried changing the CRC in main.c to the NSTC version so the hook would work on those versions but I'm having no luck. Is there another reference to the CRC somewhere I'm missing?
